# Generated by Django 5.2.4 on 2025-07-23 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_alert_days', models.PositiveIntegerField(default=15)),
                ('default_emails', models.TextField(help_text='Emails séparés par des virgules')),
            ],
        ),
        migrations.CreateModel(
            name='SmtpConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(help_text='Nom du serveur SMTP', max_length=100)),
                ('host', models.GenericIPAddressField(help_text='Adresse IP du serveur')),
                ('port', models.PositiveIntegerField(help_text='Port SMTP (ex: 25, 587, 465)')),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to='certificates.team')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('cn', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_remaining', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('notified', models.BooleanField(default=False)),
                ('custom_alert_days', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_emails', models.TextField(blank=True, help_text='Emails séparés par des virgules', null=True)),
                ('next_check_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_frequency', models.CharField(choices=[('2h', 'Toutes les 2 heures'), ('4h', 'Toutes les 4 heures'), ('8h', 'Toutes les 8 heures'), ('12h', 'Toutes les 12 heures'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='daily', max_length=20)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.team')),
            ],
        ),
    ]
