# Generated by Django 5.2.5 on 2025-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Externe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.IntegerField(unique=True)),
                ('certificate_request_ref', models.CharField(max_length=100)),
                ('certificate_target', models.CharField(max_length=50)),
                ('certificate_state', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=255)),
                ('dns', models.JSONField()),
                ('action_at', models.DateTimeField()),
                ('generated_at', models.DateTimeField()),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('is_renewed', models.BooleanField(default=False)),
                ('certificate_type', models.CharField(max_length=50)),
                ('archive_password', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField()),
                ('actor_id', models.IntegerField()),
                ('actor', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=100)),
                ('itop_ticket_num', models.IntegerField()),
                ('itop_ticket_ref', models.CharField(max_length=100)),
                ('ticket_state', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='check_frequency',
            field=models.CharField(choices=[('1h', 'Toutes'), ('2h', 'Toutes les 2 heures'), ('4h', 'Toutes les 4 heures'), ('8h', 'Toutes les 8 heures'), ('12h', 'Toutes les 12 heures'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='daily', max_length=20),
        ),
    ]
