# Generated by Django 5.2.4 on 2025-07-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cn',
            field=models.CharField(default='', max_length=255),
        ),
    ]
