# Generated by Django 5.2.5 on 2025-08-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_externe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEmailConfig',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='SmtpConfiguration',
        ),
    ]
