# Generated by Django 5.2.4 on 2025-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
